stages:
  Data Ingestion:
    cmd: python C:\final\MLOPS_Clothes_project\dataset.py
    deps:
    - MLOPS_Clothes_project\dataset.py
    outs:
    - data/raw
  features:
    cmd: python -m MLOPS_Clothes_project.features
    deps:
    - MLOPS_Clothes_project/features.py
    - data/raw/dataset.csv
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/processor.pkl
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  train:
    cmd: python -m MLOPS_Clothes_project.train
    deps:
    - MLOPS_Clothes_project/train.py
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
    outs:
    - models/model.pkl
  model_eval:
    cmd: python -m MLOPS_Clothes_project.model_eval
    deps:
    - MLOPS_Clothes_project/model_eval.py
    - data/processed/X_test.csv
    - data/processed/y_test.csv
    - models/model.pkl
    outs:
    - reports/figure/metrics.json
